version: 4.1.0.{build}
clone_depth: 10
install:
build: off
# matrix:
#   fast_finish: true

environment:
  RUBY_VER: 21-x64
  TEST_LOCALE: en-US
  matrix:
  # - TEST_LOCALE: en-US
  # - TEST_LOCALE: fr-FR
  - TEST_LOCALE: de-DE
  - TEST_LOCALE: ja-JP
  # - RUBY_VER: 23-x64

before_test:
  # Semicolons are required below.  This renders as a single line powershell command in AppVeyor
  - ps: >-
      $testLocale = [Environment]::GetEnvironmentVariable("TEST_LOCALE","Process");
      $currentLocale = (Get-WinSystemLocale).Name;
      if ($testLocale -ne $currentLocale) {
        Write-Output "Setting Locale to $testLocale ...";
        Set-WinSystemLocale ([Environment]::GetEnvironmentVariable("TEST_LOCALE","Process"));
        Write-Output "Restarting worker in 5 seconds...";
        Start-Sleep -Seconds 5
        Restart-Computer -Force -Confirm:$false;
      } else {
        Write-Output "Locale is already set to $currentLocale";
      };

test_script:
  # Changing Locales requires a reboot.  Need a delay here to allow Appveyor log message receiver to wakeup
  - ps: >-
      if ( (Get-WinSystemLocale).Name -ne 'en-US') {
        240..1 | % { Write-Output "Pause: $_"; Start-Sleep -Seconds 1 }
      }
  - REM NOOP
  - REM NOOP
  - REM NOOP
  - REM NOOP
  - REM NOOP
  - REM NOOP
  - REM NOOP
  - REM NOOP
  - REM NOOP
  - SET
  - chcp
  - ps: Get-WinSystemLocale
  - SET PATH=C:\Ruby%RUBY_VER%\bin;%PATH%
  - SET LOG_SPEC_ORDER=true
  - bundle install --jobs 4 --retry 2 --without development extra
  - type Gemfile.lock
  - ruby -v
  #- bundle exec rake parallel:spec
  - ECHO I am a meat popsicle
  - EXIT 0

on_failure:
  - appveyor PushArtifact .\spec_order.txt
notifications:
  - provider: Email
    to:
    - nobody@nowhere.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
